blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medium.urls')),  
    path('userauth/', include('userauth.urls')),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medium/urls.py
from django.urls import path
from . import views

app_name = 'medium'
urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<id>/', views.edit, name='edit'),
    path('view/<id>/', views.view, name='view'),
    path('delete/<id>/', views.delete, name='delete'),
    path('create/', views.create_blog, name='create_blog'),
    

]

userauth/urls.py
from django.urls import path
from userauth import views

app_name = 'userauth'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('baseadmin/', views.baseadmin, name='baseadmin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('usermanagement/', views.user_management, name='usermanagement'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('view_user/<int:id>/', views.view_user, name='view_user'),
    path('view_post/<int:id>/', views.view_post, name='view_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('authorinfo/', views.authorinfo, name='authorinfo'),
    path('Settings/', views.Settings, name='Settings'),
    path('unauthorized/', views.unauthorized, name='unauthorized'),
]

templates/partials/base.html
{% load static tailwind_tags %}
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Blog Page</title>

{% tailwind_css %}
    <link rel="stylesheet" href="{% static  'css/index.css'  %}">
  </head>
  <body>
    {% include "partials/navbar.html" %}
    {% block content %}
    
    
    {% endblock %}
    {% include "partials/footer.html" %}
      
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/partials/baseadmin.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Admin Dashboard</title>


  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<div class="fixed top-0 w-full h-16 bg-blue-500 flex justify-between items-center px-6 z-50">
  {% tailwind_css %}
  <div class="text-white text-xl font-semibold">
    Admin Dashboard
  </div>

  <div class="flex items-center">
    {% if request.user.image %}
    <img src="{{ request.user.image.url }}" alt="User Profile Picture" class="w-8 h-8 rounded-full">
    {% else %}
    <img src="/media/default_user.png" alt="Default User Icon" class="w-8 h-8 rounded-full">
    {% endif %}
  </div>
</div>
<div class="fixed top-16 left-0 w-48 h-[calc(100vh-4rem)] bg-white border-r shadow-md">
  <ul class="space-y-2 py-4">
    <li>
      <a href="{% url 'userauth:dashboard' %}" class="flex items-center space-x-3 text-gray-700 hover:bg-gray-100 p-2">
        <img src="/media/dashboard.png" alt="Dashboard" class="w-5 h-5"> 
        <span>Dashboard</span>
      </a>
    </li>
    <li>
      <a href="{% url 'userauth:usermanagement' %}" class="flex items-center space-x-3 text-gray-700 hover:bg-gray-100 p-2">
        <img src="/media/user.png" alt="User Management" class="w-5 h-5"> 
        <span>User Management</span>
      </a>
    </li>
    <li>
      <a href="{% url 'userauth:authorinfo' %}" class="flex items-center space-x-3 text-gray-700 hover:bg-gray-100 p-2">
        <img src="/media/author.png" alt="Authors" class="w-5 h-5"> 
        <span>Posts</span>
      </a>
    </li>
    <li>
      <a href="{% url 'userauth:Settings' %}" class="flex items-center space-x-3 text-gray-700 hover:bg-gray-100 p-2">
        <img src="/media/settings.png" alt="Settings" class="w-5 h-5"> 
        <span>Settings</span>
      </a>
    </li>
  </ul>
</div>
<div class="ml-48 mt-20 p-6">
  {% block content %}
  {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
</body>
</html>

templates/partials/footer.html
{% load static %}
{% load static tailwind_tags %}

<footer class="footer_area text-white py-8" style="background-color: #7695FF;">
    <div class="container mx-auto">
        <div class="flex flex-col items-center">
          
            <div class="footer_logo mb-6">

            </div>
            <div class="footer_social flex space-x-6 md:space-x-10 mt-4">
                <a href="https://twitter.com/Eyeroll23" target="_blank">
                    <img src="/media/twitter.png" alt="Twitter" class="h-8 w-8">
                </a>
                <a href="https://www.instagram.com/prasiddhii.dahal/" target="_blank">
                    <img src="/media/instagram.png" alt="Instagram" class="h-8 w-8">
                </a>
                <a href="https://www.linkedin.com/in/prasiddhi-dahal-1a19a3218/" target="_blank">
                    <img src="/media/linkedin.png" alt="LinkedIn" class="h-8 w-8">
                </a>
                <a href="https://github.com/Prasiddhidahal" target="_blank">
                    <img src="/media/github.png" alt="GitHub" class="h-8 w-8">
                </a>
            </div>
            
        </div>
    </div>
</footer>

templates/partials/navbar.html
{% load static %}
{% load static tailwind_tags %}
<header class="header_area text-white py-4" style="background-color: #7695FF;">
  <div class="main_menu">
    <nav class="container mx-auto flex justify-center items-center">
      <ul class="flex justify-center space-x-10 mt-4">
        {% tailwind_css %}
        <li class="nav-item"><a class="nav-link hover:text-gray-200 font-bold h5" href="{% url 'medium:index' %}">Home</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link hover:text-gray-200 font-bold h5" href="{% url 'userauth:logout' %}">Logout</a></li>
          <li class="nav-item"><a class="nav-link hover:text-gray-200 font-bold h5" href="{% url 'userauth:profile' %}">Hi, {{ request.user }}</a></li>
          <li class="nav-item"><a class="nav-link hover:text-gray-200 font-bold h5" href="{% url 'userauth:dashboard' %}">Admin Dashboard</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link hover:text-gray-200 font-bold h5" href="{% url 'userauth:login' %}"><i class="fa fa-user"></i> Login</a></li>
          <li class="nav-item"><a class="nav-link hover:text-gray-200 font-bold h5" href="{% url 'userauth:register' %}">Register</a></li>
        {% endif %}
      </ul>

      {% if user.is_authenticated %}
      <div class="ml-5">
        <a href="{% url 'medium:create_blog' %}" class="flex items-center bg-gradient-to-r from-[#9DBDFF] to-grey text-white py-2 px-4 rounded-lg hover:bg-gradient-to-l transition duration-300 bold h5">
          <img src="/media/write.png" alt="Create Blog Icon" class="w-10 h-10 mr-2">
          Create Blog
        </a>
      </div>
      {% endif %}
    </nav>
  </div>
</header>